name: 游대 Actualizar Noticias Diario

on:
  schedule:
    - cron: '0 11 * * *'  # Todos los d칤as a las 11am UTC (5am CDMX)
  workflow_dispatch:      # Tambi칠n se puede correr manualmente

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
    - name: 游닌 Clonar el repo
      uses: actions/checkout@v3

    - name: 游냀 Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 游닍 Instalar requerimientos
      run: |
        pip install -r requirements.txt
        pip install nbconvert ipykernel

    - name: 丘뙖잺 Ejecutar notebook de actualizaci칩n
      run: |
        jupyter nbconvert --execute --inplace noticias_mty_11.ipynb

    - name: 游닋 Subir cambios si los hay
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "游댃 Actualizaci칩n autom치tica de noticias [$(date +'%Y-%m-%d')]" || echo "No hay cambios"
        git push
